
// var person={
  
//   name:"serhat",
//   surname:"cetin",
//   age:35,
// //   salary:180,
// //   job:["subject","it","position","teacher","school","bedir",280]
  
  
  
// // }


// // console.log(person);
// // console.log(person.salary+50);
// // console.log(person.job[2]);
// // //console.log(person[1]);
// // console.log(500+person.job[6]);

// // var n="1345";
// // console.log(n.split("").reverse().join("_"));

// // function reverse1(n){
  
// //   n=n+"";
// //   return n.split("").reverse().join("");
  
// // }

// // console.log(reverse1(2340));


// let a=""+345;


// console.log(a.split("").reverse());

// // function reverse_a_number(n){
  
// //   n=n+"";
// //   console.log(n.split("").reverse().join(""));
  
  
// // }

// // reverse_a_number(567);




// //var s=prompt("please enter a string");

// function reverse_a_string(s){
  
  
//   console.log(s.split("").reverse().join(""));
  
  
// }

// //reverse_a_string("serpil");






// function construct_name(name,surname,salary){
  
//   this.name=name;
//   this.surname=surname;
//   this.salary=salary;
 
// }





// var con=new construct_name("serhat","cetin",180);
// console.log(con);



//push(), unshift(),pop(),shift()

// var a=["hi","hello"];
// a.push("murat");
// console.log(a);

// a.unshift("serpil");
// console.log(a);

// a.pop();
// console.log(a);

// a.shift();
// console.log(a);

// function isLeap(year){
//    if (year % 4 === 0) {
//       if (year % 100 === 0){
//          if (year % 400 == 0){
//             return ("Leap year.");
//          } else {
//             return ("Not leap year.");
//          }
//       } else {
//          return ("Leap year.");
//       }
//    } else{
//       return ("Not leap year.");
//    }
// }


// function isLeap(year){
  
//   if(year%4==0){
    
//     if(year%100==0){
      
//       if(year%400==0){
//         return ("leap year");
//       }
//       else{
//         return ("not leap year");
//       }
      
//     }else{
      
//       return (" leap yer");
//     }
//   }
//   else{
    
//     return ("not leap year");
//   }
 
// }


function isLeap(year){
    if(year%4==0){
      
      if(year%100==0){
        if(year%400==0){
          
          return ("leap year");
          
          
        }else {return ("not leap");}
        
        
      }else{
        
        
        
        return ("leap year");
      }
      
      
      
      
    }else{ return ("not leap");}
    
    
    
  }
  
  
  
  
  
  
  console.log(isLeap(400));
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

// var person={
  
//   name:"serhat",
//   surname:"cetin",
//   age:35,
// //   salary:180,
// //   job:["subject","it","position","teacher","school","bedir",280]
  
  
  
// // }


// // console.log(person);
// // console.log(person.salary+50);
// // console.log(person.job[2]);
// // //console.log(person[1]);
// // console.log(500+person.job[6]);

// // var n="1345";
// // console.log(n.split("").reverse().join("_"));

// // function reverse1(n){
  
// //   n=n+"";
// //   return n.split("").reverse().join("");
  
// // }

// // console.log(reverse1(2340));


// let a=""+345;


// console.log(a.split("").reverse());

// // function reverse_a_number(n){
  
// //   n=n+"";
// //   console.log(n.split("").reverse().join(""));
  
  
// // }

// // reverse_a_number(567);




// //var s=prompt("please enter a string");

// function reverse_a_string(s){
  
  
//   console.log(s.split("").reverse().join(""));
  
  
// }

// //reverse_a_string("serpil");






// function construct_name(name,surname,salary){
  
//   this.name=name;
//   this.surname=surname;
//   this.salary=salary;
 
// }





// var con=new construct_name("serhat","cetin",180);
// console.log(con);



//push(), unshift(),pop(),shift()

// var a=["hi","hello"];
// a.push("murat");
// console.log(a);

// a.unshift("serpil");
// console.log(a);

// a.pop();
// console.log(a);

// a.shift();
// console.log(a);

// function isLeap(year){
//    if (year % 4 === 0) {
//       if (year % 100 === 0){
//          if (year % 400 == 0){
//             return ("Leap year.");
//          } else {
//             return ("Not leap year.");
//          }
//       } else {
//          return ("Leap year.");
//       }
//    } else{
//       return ("Not leap year.");
//    }
// }


// function isLeap(year){
  
//   if(year%4==0){
    
//     if(year%100==0){
      
//       if(year%400==0){
//         return ("leap year");
//       }
//       else{
//         return ("not leap year");
//       }
      
//     }else{
      
//       return (" leap yer");
//     }
//   }
//   else{
    
//     return ("not leap year");
//   }
 
// }


function isLeap(year){
    if(year%4==0){
      
      if(year%100==0){
        if(year%400==0){
          
          return ("leap year");
          
          
        }else {return ("not leap");}
        
        
      }else{
        
        
        
        return ("leap year");
      }
      
      
      
      
    }else{ return ("not leap");}
    
    
    
  }
  
  
  
  
  
  
  console.log(isLeap(400));
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    